(ns flash-cards.core
  (:gen-class))

(def phrase-map
  (->>
    [["Hallo" "Hi" "Hey"]                     ["Hello" "Hi" "Hey"]
     "Wie geht's?"                            ["How are you?" "How's it going?"]
     "Guten Morgen"                           "Good morning"
     "Guten Tag"                              "Good day"
     "Guten Abend"                            "Good evening"
     "Gute Nacht"                             "Good night"
     "Auf Wiedersehen"                        "Goodbye"
     "Tschüss"                                "Bye"
     "Bis bald"                               "See you soon"
     "Bis morgen"                             "See you tomorrow"
     "Frankreich"                             "France"
     "Deutschland"                            "Germany"
     "Russland"                               "Russia"
     "England"                                "England"
     "Schottland"                             "Scotland"
     "Wales"                                  "Wales"
     "Irland"                                 "Ireland"
     "Polen"                                  "Poland"
     "Spanien"                                "Spain"
     "Japan"                                  "Japan"
     "China"                                  "China"
     "Amerika"                                "America"
     "Türkei"                                 "Turkey"
     "Italien"                                "Italy"
     "Großbritannien"                         "Great Britain"
     "Amerikaner"                             "American (M)"
     "Deutscher"                              "German (M)"
     "Engländer"                              "English (M)"
     "Italiener"                              "Italian (M)"
     "Japaner"                                "Japanese (M)"
     "Waliser"                                "Welsh (M)"
     "Spanier"                                "Spanish (M)"
     "Franzose"                               "French (M)"
     "Chinese"                                "Chinese (M)"
     "Brite"                                  "British (M)"
     "Pole"                                   "Polish (M)"
     "Russe"                                  "Russian (M)"
     "Schotte"                                "Scottish (M)"
     "Türke"                                  "Turkish (M)"
     "Amerikanerin"                           "American (F)"
     "Deutsche"                               "German (F)"
     "Engländerin"                            "English (F)"
     "Italienerin"                            "Italian (F)"
     "Japanerin"                              "Japenese (F)"
     "Waliserin"                              "Welsh (F)"
     "Spanierin"                              "Spanish (F)"
     "Französin"                              "French (F)"
     "Chinesin"                               "Chinese (F)"
     "Britin"                                 "British (F)"
     "Polin"                                  "Polish (F)"
     "Russin"                                 "Russian (F)"
     "Schottin"                               "Scottish (F)"
     "Türkin"                                 "Turkish (F)"
     "Englisch"                               "English"
     "Deutsch"                                "German"
     "Italienisch"                            "Italian"
     "Japanisch"                              "Japenese"
     "Walisich"                               "Welsh"
     "Spanisch"                               "Spanish"
     "Französisch"                            "French"
     "Chinesisch"                             "Chinese"
     "Polnisch"                               "Polish"
     "Russisch"                               "Russian"
     "Gälisch"                                "Gaelic"
     "Türkisch"                               "Turkish"
     ["Wie heißen Sie?" "Wie heißt du?"]      "What's your name?"
     ["Welche Sprachen sprechen Sie?" "Welche Sprachen sprichst du?"]"Which languages do you speak?"
     ["Wer bist du?" "Wer sind Sie?"]         "Who are you?"
     ["Wo wohnen Sie?" "Wo wohnst du?"]       "Where do you live?"
     ["Woher kommst du?" "Woher kommen Sie?"] "Where are you from?"
     ["Aus Irland. Und Sie?" "Aus Irland. Und du?"] "From Ireland. And you?"
     "Englisch und Deutsch"                   "English and German"
     "Mein Name ist Kunze"                    "My name is Kunze"
     ["Aus Brasilien. Und du?" "Aus Brasilien. Und Sie?"] "From Brazil. And you?"
     ["In Stuttgart. Und Sie?" "In Stuttgart. Und du?"] "In Stuttgart. And you?"
     ["In Berlin. Und du?" "In Berlin. Und Sie?"] "In Berlin. And you?"
     "Ich bin Emma Reiter"                    "I am Emma Reiter"
     ["Und wer sind Sie?" "Und wer bist du?"] "And who are you?"
     "Ich wohne in Salzburg"                  "I live in Salzburg"
     "Ich bin Peter"                          "I am Peter"]
     (map (fn [v] (if (vector? v) v [v])))
     vec))
