(ns flash-cards.phrase-map
  (:gen-class))

(defrecord Phrase [german english tags])

(def all-tags (atom '()))
(defmacro deftag [sym]
  (do
    (swap! all-tags (partial cons (str sym)))
    `(def ~(second `(name ~sym)) ~(str sym))))

(deftag greetings)
(deftag partings)
(deftag nationalities)
(deftag languages)
(deftag countries)

(def phrase-map
   [(Phrase. ["Hallo" "Hi" "Hey"] ["Hello" "Hi" "Hey"] [greetings])
    (Phrase. ["Wie geht's?"] ["How are you?" "How's it going?"] [greetings])
    (Phrase. ["Guten Morgen"] ["Good morning"] [greetings])
    (Phrase. ["Guten Tag"] ["Good day"] [greetings])
    (Phrase. ["Guten Abend"] ["Good evening"] [greetings])
    (Phrase. ["Gute Nacht"] ["Good night"] [partings])
    (Phrase. ["Auf Wiedersehen"] ["Goodbye"] [partings])
    (Phrase. ["Tschüss"] ["Bye"] [partings])
    (Phrase. ["Bis bald"] ["See you soon"] [partings])
    (Phrase. ["Bis morgen"] ["See you tomorrow"] [partings])
    (Phrase. ["Frankreich"] ["France"] [countries])
    (Phrase. ["Deutschland"] ["Germany"] [countries])
    (Phrase. ["Russland"] ["Russia"] [countries])
    (Phrase. ["England"] ["England"] [countries])
    (Phrase. ["Schottland"] ["Scotland"] [countries])
    (Phrase. ["Wales"] ["Wales"] [countries])
    (Phrase. ["Irland"] ["Ireland"] [countries])
    (Phrase. ["Polen"] ["Poland"] [countries])
    (Phrase. ["Spanien"] ["Spain"] [countries])
    (Phrase. ["Japan"] ["Japan"] [countries])
    (Phrase. ["China"] ["China"] [countries])
    (Phrase. ["Amerika"] ["America"] [countries])
    (Phrase. ["Türkei"] ["Turkey"] [countries])
    (Phrase. ["Italien"] ["Italy"] [countries])
    (Phrase. ["Großbritannien"] ["Great Britain"] [countries])
    (Phrase. ["Amerikaner"] ["American (M)"] [nationalities])
    (Phrase. ["Deutscher"] ["German (M)"] [nationalities])
    (Phrase. ["Engländer"] ["English (M)"] [nationalities])
    (Phrase. ["Italiener"] ["Italian (M)"] [nationalities])
    (Phrase. ["Japaner"] ["Japanese (M)"] [nationalities])
    (Phrase. ["Waliser"] ["Welsh (M)"] [nationalities])
    (Phrase. ["Spanier"] ["Spanish (M)"] [nationalities])
    (Phrase. ["Franzose"] ["French (M)"] [nationalities])
    (Phrase. ["Chinese"] ["Chinese (M)"] [nationalities])
    (Phrase. ["Brite"] ["British (M)"] [nationalities])
    (Phrase. ["Pole"] ["Polish (M)"] [nationalities])
    (Phrase. ["Russe"] ["Russian (M)"] [nationalities])
    (Phrase. ["Schotte"] ["Scottish (M)"] [nationalities])
    (Phrase. ["Türke"] ["Turkish (M)"] [nationalities])
    (Phrase. ["Amerikanerin"] ["American (F)"] [nationalities])
    (Phrase. ["Deutsche"] ["German (F)"] [nationalities])
    (Phrase. ["Engländerin"] ["English (F)"] [nationalities])
    (Phrase. ["Italienerin"] ["Italian (F)"] [nationalities])
    (Phrase. ["Japanerin"] ["Japenese (F)"] [nationalities])
    (Phrase. ["Waliserin"] ["Welsh (F)"] [nationalities])
    (Phrase. ["Spanierin"] ["Spanish (F)"] [nationalities])
    (Phrase. ["Französin"] ["French (F)"] [nationalities])
    (Phrase. ["Chinesin"] ["Chinese (F)"] [nationalities])
    (Phrase. ["Britin"] ["British (F)"] [nationalities])
    (Phrase. ["Polin"] ["Polish (F)"] [nationalities])
    (Phrase. ["Russin"] ["Russian (F)"] [nationalities])
    (Phrase. ["Schottin"] ["Scottish (F)"] [nationalities])
    (Phrase. ["Türkin"] ["Turkish (F)"] [nationalities])
    (Phrase. ["Englisch"] ["English"] [languages])
    (Phrase. ["Deutsch"] ["German"] [languages])
    (Phrase. ["Italienisch"] ["Italian"] [languages])
    (Phrase. ["Japanisch"] ["Japenese"] [languages])
    (Phrase. ["Walisich"] ["Welsh"] [languages])
    (Phrase. ["Spanisch"] ["Spanish"] [languages])
    (Phrase. ["Französisch"] ["French"] [languages])
    (Phrase. ["Chinesisch"] ["Chinese"] [languages])
    (Phrase. ["Polnisch"] ["Polish"] [languages])
    (Phrase. ["Russisch"] ["Russian"] [languages])
    (Phrase. ["Gälisch"] ["Gaelic"] [languages])
    (Phrase. ["Türkisch"] ["Turkish"] [languages])
    (Phrase. ["Wie heißen Sie?" "Wie heißt du?"] ["What's your name?"] [])
    (Phrase. ["Welche Sprachen sprechen Sie?" "Welche Sprachen sprichst du?"] ["Which languages do you speak?"] [])
    (Phrase. ["Wer bist du?" "Wer sind Sie?"] ["Who are you?"] [])
    (Phrase. ["Wo wohnen Sie?" "Wo wohnst du?"] ["Where do you live?"] [])
    (Phrase. ["Woher kommst du?" "Woher kommen Sie?"] ["Where are you from?"] [])
    (Phrase. ["Aus Irland. Und Sie?" "Aus Irland. Und du?"] ["From Ireland. And you?"] [])
    (Phrase. ["Englisch und Deutsch"] ["English and German"] [])
    (Phrase. ["Mein Name ist Kunze"] ["My name is Kunze"] [])
    (Phrase. ["Aus Brasilien. Und du?" "Aus Brasilien. Und Sie?"] ["From Brazil. And you?"] [])
    (Phrase. ["In Stuttgart. Und Sie?" "In Stuttgart. Und du?"] ["In Stuttgart. And you?"] [])
    (Phrase. ["In Berlin. Und du?" "In Berlin. Und Sie?"] ["In Berlin. And you?"] [])
    (Phrase. ["Ich bin Emma Reiter"] ["I am Emma Reiter"] [])
    (Phrase. ["Und wer sind Sie?" "Und wer bist du?"] ["And who are you?"] [])
    (Phrase. ["Ich wohne in Salzburg"] ["I live in Salzburg"] [])
    (Phrase. ["Ich bin Peter"] ["I am Peter"] [])])
