(ns flash-cards.core
  (:gen-class))

(def word-map
  ["Hallo"          "Hello"
   "Wie geht's?"    "How are you?"
   "Frankreich"     "France"
   "Deutschland"    "Germany"
   "Russland"       "Russia"
   "England"        "England"
   "Schottland"     "Scotland"
   "Wales"          "Wales"
   "Irland"         "Ireland"
   "Polen"          "Poland"
   "Spanien"        "Spain"
   "Japan"          "Japan"
   "China"          "China"
   "Amerika"        "America"
   "Türkei"         "Turkey"
   "Italien"        "Italy"
   "Großbritannien" "Great Britain"
   "Amerikaner"     "American (M)"
   "Deutscher"      "German (M)"
   "Engländer"      "English (M)"
   "Italiener"      "Italian (M)"
   "Japaner"        "Japanese (M)"
   "Waliser"        "Welsh (M)"
   "Spanier"        "Spanish (M)"
   "Franzose"       "French (M)"
   "Chinese"        "Chinese (M)"
   "Brite"          "British (M)"
   "Pole"           "Polish (M)"
   "Russe"          "Russian (M)"
   "Schotte"        "Scottish (M)"
   "Türke"          "Turkish (M)"
   "Amerikanerin"   "American (F)"
   "Deutsche"       "German (F)"
   "Engländerin"    "English (F)"
   "Italienerin"    "Italian (F)"
   "Japanerin"      "Japenese (F)"
   "Waliserin"      "Welsh (F)"
   "Spanierin"      "Spanish (F)"
   "Französin"      "French (F)"
   "Chinesin"       "Chinese (F)"
   "Britin"         "British (F)"
   "Polin"          "Polish (F)"
   "Russin"         "Russian (F)"
   "Schottin"       "Scottish (F)"
   "Türkin"         "Turkish (F)"
   "Englisch"       "English"
   "Deutsch"        "German"
   "Italienisch"    "Italian"
   "Japanisch"      "Japenese"
   "Walisich"       "Welsh"
   "Spanisch"       "Spanish"
   "Französisch"    "French"
   "Chinesisch"     "Chinese"
   "Polnisch"       "Polish"
   "Russisch"       "Russian"
   "Gälisch"        "Gaelic"
   "Türkisch"       "Turkish"])
